// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: db_reqres.proto

package pbm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`       // 유저 이메일
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"` // 유저 닉네임
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`       // 유저 프로필 이미지
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqLogin) Reset() {
	*x = ReqLogin{}
	mi := &file_db_reqres_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogin) ProtoMessage() {}

func (x *ReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogin.ProtoReflect.Descriptor instead.
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{0}
}

func (x *ReqLogin) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReqLogin) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ReqLogin) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type ResLogin struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uid            int32                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                      // 유저 인덱스 아이디
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                   // 유저 이메일
	Nickname       string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`             // 유저 닉네임
	Image          string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`                   // 유저 프로필 이미지
	Account        string                 `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`               // 유저 계좌
	TotalMoney     float32                `protobuf:"fixed32,6,opt,name=totalMoney,proto3" json:"totalMoney,omitempty"`       // 금액
	IsSubscribe    string                 `protobuf:"bytes,7,opt,name=isSubscribe,proto3" json:"isSubscribe,omitempty"`       // 구독 여부
	SubscribeAt    string                 `protobuf:"bytes,8,opt,name=subscribeAt,proto3" json:"subscribeAt,omitempty"`       // 구독 시작
	SubscribeEndAt string                 `protobuf:"bytes,9,opt,name=subscribeEndAt,proto3" json:"subscribeEndAt,omitempty"` // 구독 종료
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResLogin) Reset() {
	*x = ResLogin{}
	mi := &file_db_reqres_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResLogin) ProtoMessage() {}

func (x *ResLogin) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResLogin.ProtoReflect.Descriptor instead.
func (*ResLogin) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{1}
}

func (x *ResLogin) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ResLogin) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResLogin) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ResLogin) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ResLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ResLogin) GetTotalMoney() float32 {
	if x != nil {
		return x.TotalMoney
	}
	return 0
}

func (x *ResLogin) GetIsSubscribe() string {
	if x != nil {
		return x.IsSubscribe
	}
	return ""
}

func (x *ResLogin) GetSubscribeAt() string {
	if x != nil {
		return x.SubscribeAt
	}
	return ""
}

func (x *ResLogin) GetSubscribeEndAt() string {
	if x != nil {
		return x.SubscribeEndAt
	}
	return ""
}

type ResProfile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uid            int32                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                      // 유저 인덱스 아이디
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                   // 유저 이메일
	Nickname       string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`             // 유저 닉네임
	Image          string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`                   // 유저 프로필 이미지
	Account        string                 `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`               // 유저 계좌
	TotalMoney     float32                `protobuf:"fixed32,6,opt,name=totalMoney,proto3" json:"totalMoney,omitempty"`       // 금액
	IsSubscribe    string                 `protobuf:"bytes,7,opt,name=isSubscribe,proto3" json:"isSubscribe,omitempty"`       // 구독 여부
	SubscribeAt    string                 `protobuf:"bytes,8,opt,name=subscribeAt,proto3" json:"subscribeAt,omitempty"`       // 구독 시작
	SubscribeEndAt string                 `protobuf:"bytes,9,opt,name=subscribeEndAt,proto3" json:"subscribeEndAt,omitempty"` // 구독 종료
	Games          int32                  `protobuf:"varint,10,opt,name=games,proto3" json:"games,omitempty"`                 // 총 게임 횟수
	Win            int32                  `protobuf:"varint,11,opt,name=win,proto3" json:"win,omitempty"`                     // 총 승리 횟수
	Defeat         int32                  `protobuf:"varint,12,opt,name=defeat,proto3" json:"defeat,omitempty"`               // 총 패배 횟수
	Draw           int32                  `protobuf:"varint,13,opt,name=draw,proto3" json:"draw,omitempty"`                   // 총 비김 횟수
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResProfile) Reset() {
	*x = ResProfile{}
	mi := &file_db_reqres_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResProfile) ProtoMessage() {}

func (x *ResProfile) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResProfile.ProtoReflect.Descriptor instead.
func (*ResProfile) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{2}
}

func (x *ResProfile) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ResProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ResProfile) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ResProfile) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ResProfile) GetTotalMoney() float32 {
	if x != nil {
		return x.TotalMoney
	}
	return 0
}

func (x *ResProfile) GetIsSubscribe() string {
	if x != nil {
		return x.IsSubscribe
	}
	return ""
}

func (x *ResProfile) GetSubscribeAt() string {
	if x != nil {
		return x.SubscribeAt
	}
	return ""
}

func (x *ResProfile) GetSubscribeEndAt() string {
	if x != nil {
		return x.SubscribeEndAt
	}
	return ""
}

func (x *ResProfile) GetGames() int32 {
	if x != nil {
		return x.Games
	}
	return 0
}

func (x *ResProfile) GetWin() int32 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *ResProfile) GetDefeat() int32 {
	if x != nil {
		return x.Defeat
	}
	return 0
}

func (x *ResProfile) GetDraw() int32 {
	if x != nil {
		return x.Draw
	}
	return 0
}

type ResServers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           int32                  `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`          // 서버 정보 아이디
	AppId         string                 `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`       // 앱 아이디 com.dofiang.episode01~05
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`           // 서버 주소
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`     // 지역
	Sort          int32                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`        // 정렬
	CreateAt      string                 `protobuf:"bytes,6,opt,name=createAt,proto3" json:"createAt,omitempty"` // 생성일
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResServers) Reset() {
	*x = ResServers{}
	mi := &file_db_reqres_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResServers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResServers) ProtoMessage() {}

func (x *ResServers) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResServers.ProtoReflect.Descriptor instead.
func (*ResServers) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{3}
}

func (x *ResServers) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ResServers) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ResServers) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ResServers) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ResServers) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ResServers) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type ReqUpdateBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int32                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`      // 유저 인덱스 아이디
	Money         float32                `protobuf:"fixed32,2,opt,name=money,proto3" json:"money,omitempty"` // + - 금액
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUpdateBalance) Reset() {
	*x = ReqUpdateBalance{}
	mi := &file_db_reqres_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUpdateBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdateBalance) ProtoMessage() {}

func (x *ReqUpdateBalance) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpdateBalance.ProtoReflect.Descriptor instead.
func (*ReqUpdateBalance) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{4}
}

func (x *ReqUpdateBalance) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqUpdateBalance) GetMoney() float32 {
	if x != nil {
		return x.Money
	}
	return 0
}

type ResDeckList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decklist      []*ReqResDeck          `protobuf:"bytes,1,rep,name=decklist,proto3" json:"decklist,omitempty"` // 덱 리스트
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResDeckList) Reset() {
	*x = ResDeckList{}
	mi := &file_db_reqres_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResDeckList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResDeckList) ProtoMessage() {}

func (x *ResDeckList) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResDeckList.ProtoReflect.Descriptor instead.
func (*ResDeckList) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{5}
}

func (x *ResDeckList) GetDecklist() []*ReqResDeck {
	if x != nil {
		return x.Decklist
	}
	return nil
}

type ResFavoriteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FavoriteList  []*ReqResFavorities    `protobuf:"bytes,1,rep,name=favoriteList,proto3" json:"favoriteList,omitempty"` // 관심 카드 리스트
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResFavoriteList) Reset() {
	*x = ResFavoriteList{}
	mi := &file_db_reqres_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResFavoriteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResFavoriteList) ProtoMessage() {}

func (x *ResFavoriteList) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResFavoriteList.ProtoReflect.Descriptor instead.
func (*ResFavoriteList) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{6}
}

func (x *ResFavoriteList) GetFavoriteList() []*ReqResFavorities {
	if x != nil {
		return x.FavoriteList
	}
	return nil
}

type ReqResDeckDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ddid          int32                  `protobuf:"varint,1,opt,name=ddid,proto3" json:"ddid,omitempty"`              // 덱 상세 아이디
	Dmid          int32                  `protobuf:"varint,2,opt,name=dmid,proto3" json:"dmid,omitempty"`              // 덱 마스터 아이디
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`           // 덱 카드 코드
	Exchange      string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`       // 덱 카드 거래소 코드
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`               // 덱 카드 이름
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`           // 덱 선택당시 카드 금액
	Change        float32                `protobuf:"fixed32,7,opt,name=change,proto3" json:"change,omitempty"`         // 덱 변화
	ChangeRate    float32                `protobuf:"fixed32,8,opt,name=changeRate,proto3" json:"changeRate,omitempty"` // 덱 변화율
	CreateAt      string                 `protobuf:"bytes,9,opt,name=createAt,proto3" json:"createAt,omitempty"`       // 덱 적용일
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqResDeckDetails) Reset() {
	*x = ReqResDeckDetails{}
	mi := &file_db_reqres_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqResDeckDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqResDeckDetails) ProtoMessage() {}

func (x *ReqResDeckDetails) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqResDeckDetails.ProtoReflect.Descriptor instead.
func (*ReqResDeckDetails) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{7}
}

func (x *ReqResDeckDetails) GetDdid() int32 {
	if x != nil {
		return x.Ddid
	}
	return 0
}

func (x *ReqResDeckDetails) GetDmid() int32 {
	if x != nil {
		return x.Dmid
	}
	return 0
}

func (x *ReqResDeckDetails) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ReqResDeckDetails) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *ReqResDeckDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqResDeckDetails) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ReqResDeckDetails) GetChange() float32 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *ReqResDeckDetails) GetChangeRate() float32 {
	if x != nil {
		return x.ChangeRate
	}
	return 0
}

func (x *ReqResDeckDetails) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type ReqResDeck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dmid          int32                  `protobuf:"varint,1,opt,name=dmid,proto3" json:"dmid,omitempty"`              // 덱 마스터 아이디
	Uid           int32                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                // 덱 유저 아이디
	AppId         string                 `protobuf:"bytes,3,opt,name=appId,proto3" json:"appId,omitempty"`             // 앱 아이디 com.dofiang.episode01~05
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`               // 덱 이름
	CreateAt      string                 `protobuf:"bytes,6,opt,name=createAt,proto3" json:"createAt,omitempty"`       // 덱 생성일
	ModifyAt      string                 `protobuf:"bytes,7,opt,name=modifyAt,proto3" json:"modifyAt,omitempty"`       // 덱 수정일
	DeleteAt      string                 `protobuf:"bytes,8,opt,name=deleteAt,proto3" json:"deleteAt,omitempty"`       // 덱 삭제일
	DeckDetails   []*ReqResDeckDetails   `protobuf:"bytes,9,rep,name=deckDetails,proto3" json:"deckDetails,omitempty"` // 덱 상세 리스트
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqResDeck) Reset() {
	*x = ReqResDeck{}
	mi := &file_db_reqres_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqResDeck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqResDeck) ProtoMessage() {}

func (x *ReqResDeck) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqResDeck.ProtoReflect.Descriptor instead.
func (*ReqResDeck) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{8}
}

func (x *ReqResDeck) GetDmid() int32 {
	if x != nil {
		return x.Dmid
	}
	return 0
}

func (x *ReqResDeck) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqResDeck) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ReqResDeck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqResDeck) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *ReqResDeck) GetModifyAt() string {
	if x != nil {
		return x.ModifyAt
	}
	return ""
}

func (x *ReqResDeck) GetDeleteAt() string {
	if x != nil {
		return x.DeleteAt
	}
	return ""
}

func (x *ReqResDeck) GetDeckDetails() []*ReqResDeckDetails {
	if x != nil {
		return x.DeckDetails
	}
	return nil
}

type ReqResFavorities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           int32                  `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`                // 관심 카드 아이디
	Uid           int32                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                // 관심 카드 유저 아이디
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`           // 관심 카드 코드
	Exchange      string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`       // 관심 카드 거래소 코드
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`               // 관심 카드 이름
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`           // 관심 선택당시 카드 금액
	Change        float32                `protobuf:"fixed32,7,opt,name=change,proto3" json:"change,omitempty"`         // 관심 변화
	ChangeRate    float32                `protobuf:"fixed32,8,opt,name=changeRate,proto3" json:"changeRate,omitempty"` // 관심 변화율
	CreateAt      string                 `protobuf:"bytes,9,opt,name=createAt,proto3" json:"createAt,omitempty"`       // 관심 적용일
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqResFavorities) Reset() {
	*x = ReqResFavorities{}
	mi := &file_db_reqres_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqResFavorities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqResFavorities) ProtoMessage() {}

func (x *ReqResFavorities) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqResFavorities.ProtoReflect.Descriptor instead.
func (*ReqResFavorities) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{9}
}

func (x *ReqResFavorities) GetFid() int32 {
	if x != nil {
		return x.Fid
	}
	return 0
}

func (x *ReqResFavorities) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqResFavorities) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ReqResFavorities) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *ReqResFavorities) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqResFavorities) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ReqResFavorities) GetChange() float32 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *ReqResFavorities) GetChangeRate() float32 {
	if x != nil {
		return x.ChangeRate
	}
	return 0
}

func (x *ReqResFavorities) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type ReqPurchases struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int32                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`            // 구매 유저 아이디
	ProductId     string                 `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"` // 구매 상품 코드 S30, S45, S60, S120, C1000...
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`       // 구매 금액
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqPurchases) Reset() {
	*x = ReqPurchases{}
	mi := &file_db_reqres_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqPurchases) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPurchases) ProtoMessage() {}

func (x *ReqPurchases) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPurchases.ProtoReflect.Descriptor instead.
func (*ReqPurchases) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{10}
}

func (x *ReqPurchases) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqPurchases) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ReqPurchases) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

// REQBY
type ReqByUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int32                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // 유저아이디
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqByUID) Reset() {
	*x = ReqByUID{}
	mi := &file_db_reqres_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqByUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqByUID) ProtoMessage() {}

func (x *ReqByUID) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqByUID.ProtoReflect.Descriptor instead.
func (*ReqByUID) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{11}
}

func (x *ReqByUID) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ReqByAppID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"` // 앱 아이디 com.dofiang.episode01~05
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqByAppID) Reset() {
	*x = ReqByAppID{}
	mi := &file_db_reqres_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqByAppID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqByAppID) ProtoMessage() {}

func (x *ReqByAppID) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqByAppID.ProtoReflect.Descriptor instead.
func (*ReqByAppID) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{12}
}

func (x *ReqByAppID) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type ReqByAppIDandUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int32                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`    // 유저 인덱스 아이디
	AppId         string                 `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"` // 앱 아이디 com.dofiang.episode01~05
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqByAppIDandUID) Reset() {
	*x = ReqByAppIDandUID{}
	mi := &file_db_reqres_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqByAppIDandUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqByAppIDandUID) ProtoMessage() {}

func (x *ReqByAppIDandUID) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqByAppIDandUID.ProtoReflect.Descriptor instead.
func (*ReqByAppIDandUID) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{13}
}

func (x *ReqByAppIDandUID) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqByAppIDandUID) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type ReqByDeckMastersID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dmid          int32                  `protobuf:"varint,1,opt,name=dmid,proto3" json:"dmid,omitempty"` // 덱 마스터 아이디
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqByDeckMastersID) Reset() {
	*x = ReqByDeckMastersID{}
	mi := &file_db_reqres_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqByDeckMastersID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqByDeckMastersID) ProtoMessage() {}

func (x *ReqByDeckMastersID) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqByDeckMastersID.ProtoReflect.Descriptor instead.
func (*ReqByDeckMastersID) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{14}
}

func (x *ReqByDeckMastersID) GetDmid() int32 {
	if x != nil {
		return x.Dmid
	}
	return 0
}

type ReqBySymbolAndUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int32                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`      // 유저아이디
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"` // 관심 카드 코드
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqBySymbolAndUID) Reset() {
	*x = ReqBySymbolAndUID{}
	mi := &file_db_reqres_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqBySymbolAndUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqBySymbolAndUID) ProtoMessage() {}

func (x *ReqBySymbolAndUID) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqBySymbolAndUID.ProtoReflect.Descriptor instead.
func (*ReqBySymbolAndUID) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{15}
}

func (x *ReqBySymbolAndUID) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqBySymbolAndUID) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type ReqResSnapshotLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slid          int32                  `protobuf:"varint,1,opt,name=slid,proto3" json:"slid,omitempty"`
	Snapshot      string                 `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	CreateAt      string                 `protobuf:"bytes,4,opt,name=createAt,proto3" json:"createAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqResSnapshotLogs) Reset() {
	*x = ReqResSnapshotLogs{}
	mi := &file_db_reqres_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqResSnapshotLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqResSnapshotLogs) ProtoMessage() {}

func (x *ReqResSnapshotLogs) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqResSnapshotLogs.ProtoReflect.Descriptor instead.
func (*ReqResSnapshotLogs) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{16}
}

func (x *ReqResSnapshotLogs) GetSlid() int32 {
	if x != nil {
		return x.Slid
	}
	return 0
}

func (x *ReqResSnapshotLogs) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *ReqResSnapshotLogs) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ReqResSnapshotLogs) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type ReqBySymbol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqBySymbol) Reset() {
	*x = ReqBySymbol{}
	mi := &file_db_reqres_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqBySymbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqBySymbol) ProtoMessage() {}

func (x *ReqBySymbol) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqBySymbol.ProtoReflect.Descriptor instead.
func (*ReqBySymbol) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{17}
}

func (x *ReqBySymbol) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ReqBySymbol) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type ResSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             string                 `protobuf:"bytes,1,opt,name=n,proto3" json:"n,omitempty"`       // 종목명
	Ne            string                 `protobuf:"bytes,2,opt,name=ne,proto3" json:"ne,omitempty"`     // 종목명영문
	S             string                 `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`       // 심볼(종목코드드)
	E             string                 `protobuf:"bytes,4,opt,name=e,proto3" json:"e,omitempty"`       // 거래소 ex(KOSPI, KOSDAQ, NYSE, NASDAQ)
	C             float64                `protobuf:"fixed64,5,opt,name=c,proto3" json:"c,omitempty"`     // 등락차이
	Cr            float64                `protobuf:"fixed64,6,opt,name=cr,proto3" json:"cr,omitempty"`   // 등락률
	Pcp           float64                `protobuf:"fixed64,7,opt,name=pcp,proto3" json:"pcp,omitempty"` // 전일자종가
	Cp            float64                `protobuf:"fixed64,8,opt,name=cp,proto3" json:"cp,omitempty"`   // 현재가(현재종가)
	Op            float64                `protobuf:"fixed64,9,opt,name=op,proto3" json:"op,omitempty"`   // 시가
	Hp            float64                `protobuf:"fixed64,10,opt,name=hp,proto3" json:"hp,omitempty"`  // 고가
	Lp            float64                `protobuf:"fixed64,11,opt,name=lp,proto3" json:"lp,omitempty"`  // 저가가
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResSnapshot) Reset() {
	*x = ResSnapshot{}
	mi := &file_db_reqres_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResSnapshot) ProtoMessage() {}

func (x *ResSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResSnapshot.ProtoReflect.Descriptor instead.
func (*ResSnapshot) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{18}
}

func (x *ResSnapshot) GetN() string {
	if x != nil {
		return x.N
	}
	return ""
}

func (x *ResSnapshot) GetNe() string {
	if x != nil {
		return x.Ne
	}
	return ""
}

func (x *ResSnapshot) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *ResSnapshot) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

func (x *ResSnapshot) GetC() float64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *ResSnapshot) GetCr() float64 {
	if x != nil {
		return x.Cr
	}
	return 0
}

func (x *ResSnapshot) GetPcp() float64 {
	if x != nil {
		return x.Pcp
	}
	return 0
}

func (x *ResSnapshot) GetCp() float64 {
	if x != nil {
		return x.Cp
	}
	return 0
}

func (x *ResSnapshot) GetOp() float64 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *ResSnapshot) GetHp() float64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *ResSnapshot) GetLp() float64 {
	if x != nil {
		return x.Lp
	}
	return 0
}

type ResSnapshots struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*ResSnapshot         `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResSnapshots) Reset() {
	*x = ResSnapshots{}
	mi := &file_db_reqres_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResSnapshots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResSnapshots) ProtoMessage() {}

func (x *ResSnapshots) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResSnapshots.ProtoReflect.Descriptor instead.
func (*ResSnapshots) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{19}
}

func (x *ResSnapshots) GetSnapshots() []*ResSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type ReqResRatios struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           int32                  `protobuf:"varint,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Ratio         string                 `protobuf:"bytes,2,opt,name=ratio,proto3" json:"ratio,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	CreateAt      string                 `protobuf:"bytes,4,opt,name=createAt,proto3" json:"createAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqResRatios) Reset() {
	*x = ReqResRatios{}
	mi := &file_db_reqres_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqResRatios) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqResRatios) ProtoMessage() {}

func (x *ReqResRatios) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqResRatios.ProtoReflect.Descriptor instead.
func (*ReqResRatios) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{20}
}

func (x *ReqResRatios) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *ReqResRatios) GetRatio() string {
	if x != nil {
		return x.Ratio
	}
	return ""
}

func (x *ReqResRatios) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ReqResRatios) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type ResRatios struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S             string                 `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`       // 심볼(종목코드드)
	Cp            float64                `protobuf:"fixed64,2,opt,name=cp,proto3" json:"cp,omitempty"`   // 현재가(현재종가)
	C             float64                `protobuf:"fixed64,3,opt,name=c,proto3" json:"c,omitempty"`     // 등락차이
	Cr            float64                `protobuf:"fixed64,4,opt,name=cr,proto3" json:"cr,omitempty"`   // 등락률
	Eps           float64                `protobuf:"fixed64,5,opt,name=eps,proto3" json:"eps,omitempty"` // EPS
	Per           float64                `protobuf:"fixed64,6,opt,name=per,proto3" json:"per,omitempty"` // PBR
	Bps           float64                `protobuf:"fixed64,7,opt,name=bps,proto3" json:"bps,omitempty"` // BPS
	Pbr           float64                `protobuf:"fixed64,8,opt,name=pbr,proto3" json:"pbr,omitempty"` // PBR
	D             float64                `protobuf:"fixed64,9,opt,name=d,proto3" json:"d,omitempty"`     // 주당배당금
	Dr            float64                `protobuf:"fixed64,10,opt,name=dr,proto3" json:"dr,omitempty"`  // 배당수익률률
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResRatios) Reset() {
	*x = ResRatios{}
	mi := &file_db_reqres_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResRatios) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResRatios) ProtoMessage() {}

func (x *ResRatios) ProtoReflect() protoreflect.Message {
	mi := &file_db_reqres_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResRatios.ProtoReflect.Descriptor instead.
func (*ResRatios) Descriptor() ([]byte, []int) {
	return file_db_reqres_proto_rawDescGZIP(), []int{21}
}

func (x *ResRatios) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *ResRatios) GetCp() float64 {
	if x != nil {
		return x.Cp
	}
	return 0
}

func (x *ResRatios) GetC() float64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *ResRatios) GetCr() float64 {
	if x != nil {
		return x.Cr
	}
	return 0
}

func (x *ResRatios) GetEps() float64 {
	if x != nil {
		return x.Eps
	}
	return 0
}

func (x *ResRatios) GetPer() float64 {
	if x != nil {
		return x.Per
	}
	return 0
}

func (x *ResRatios) GetBps() float64 {
	if x != nil {
		return x.Bps
	}
	return 0
}

func (x *ResRatios) GetPbr() float64 {
	if x != nil {
		return x.Pbr
	}
	return 0
}

func (x *ResRatios) GetD() float64 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *ResRatios) GetDr() float64 {
	if x != nil {
		return x.Dr
	}
	return 0
}

var File_db_reqres_proto protoreflect.FileDescriptor

var file_db_reqres_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x62, 0x5f, 0x72, 0x65, 0x71, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x52, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x8a, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x73, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x6e, 0x64, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x6e, 0x64,
	0x41, 0x74, 0x22, 0xe0, 0x02, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x73, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x6e, 0x64, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x6e, 0x64, 0x41,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x77, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x66,
	0x65, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x65, 0x66, 0x65, 0x61,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x72, 0x61, 0x77, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x64, 0x72, 0x61, 0x77, 0x22, 0x8e, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x3a, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x22, 0x36, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x44, 0x65, 0x63, 0x6b, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x27, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x44, 0x65, 0x63, 0x6b,
	0x52, 0x08, 0x64, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x0f, 0x52, 0x65,
	0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x35, 0x0a,
	0x0c, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x46, 0x61, 0x76, 0x6f,
	0x72, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x0c, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0xed, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x44,
	0x65, 0x63, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x64,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x64, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x6d,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x74, 0x22, 0xe6, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x44,
	0x65, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x64, 0x6d, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x12, 0x34, 0x0a, 0x0b, 0x64, 0x65, 0x63, 0x6b, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x52,
	0x65, 0x71, 0x52, 0x65, 0x73, 0x44, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x0b, 0x64, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0xe8, 0x01,
	0x0a, 0x10, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x66, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x54, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x50,
	0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x1c,
	0x0a, 0x08, 0x52, 0x65, 0x71, 0x42, 0x79, 0x55, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x0a,
	0x52, 0x65, 0x71, 0x42, 0x79, 0x41, 0x70, 0x70, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64,
	0x22, 0x3a, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x42, 0x79, 0x41, 0x70, 0x70, 0x49, 0x44, 0x61, 0x6e,
	0x64, 0x55, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x12,
	0x52, 0x65, 0x71, 0x42, 0x79, 0x44, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x73,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x64, 0x6d, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x42, 0x79, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x41, 0x6e, 0x64, 0x55, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x78, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6c, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22,
	0x3d, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x42, 0x79, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0xb7,
	0x01, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x0c,
	0x0a, 0x01, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x65, 0x12, 0x0c, 0x0a, 0x01,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x01, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x02, 0x63, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x63, 0x70, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x03, 0x70, 0x63, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x70, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x63, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x68, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6c, 0x70, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x6c, 0x70, 0x22, 0x3a, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x12, 0x2a, 0x0a, 0x09, 0x73, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x52, 0x65,
	0x73, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x09, 0x73, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x73, 0x22, 0x6a, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x52, 0x61,
	0x74, 0x69, 0x6f, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74,
	0x22, 0xad, 0x01, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x73, 0x12, 0x0c,
	0x0a, 0x01, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x63, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x63, 0x70, 0x12, 0x0c, 0x0a, 0x01,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x63, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x70,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x65, 0x70, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x70, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x62, 0x70, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x62, 0x70, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x62, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x70,
	0x62, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x64, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x64, 0x72,
	0x42, 0x0f, 0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x6d, 0xaa, 0x02, 0x03, 0x50, 0x62,
	0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_db_reqres_proto_rawDescOnce sync.Once
	file_db_reqres_proto_rawDescData = file_db_reqres_proto_rawDesc
)

func file_db_reqres_proto_rawDescGZIP() []byte {
	file_db_reqres_proto_rawDescOnce.Do(func() {
		file_db_reqres_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_reqres_proto_rawDescData)
	})
	return file_db_reqres_proto_rawDescData
}

var file_db_reqres_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_db_reqres_proto_goTypes = []any{
	(*ReqLogin)(nil),           // 0: ReqLogin
	(*ResLogin)(nil),           // 1: ResLogin
	(*ResProfile)(nil),         // 2: ResProfile
	(*ResServers)(nil),         // 3: ResServers
	(*ReqUpdateBalance)(nil),   // 4: ReqUpdateBalance
	(*ResDeckList)(nil),        // 5: ResDeckList
	(*ResFavoriteList)(nil),    // 6: ResFavoriteList
	(*ReqResDeckDetails)(nil),  // 7: ReqResDeckDetails
	(*ReqResDeck)(nil),         // 8: ReqResDeck
	(*ReqResFavorities)(nil),   // 9: ReqResFavorities
	(*ReqPurchases)(nil),       // 10: ReqPurchases
	(*ReqByUID)(nil),           // 11: ReqByUID
	(*ReqByAppID)(nil),         // 12: ReqByAppID
	(*ReqByAppIDandUID)(nil),   // 13: ReqByAppIDandUID
	(*ReqByDeckMastersID)(nil), // 14: ReqByDeckMastersID
	(*ReqBySymbolAndUID)(nil),  // 15: ReqBySymbolAndUID
	(*ReqResSnapshotLogs)(nil), // 16: ReqResSnapshotLogs
	(*ReqBySymbol)(nil),        // 17: ReqBySymbol
	(*ResSnapshot)(nil),        // 18: ResSnapshot
	(*ResSnapshots)(nil),       // 19: ResSnapshots
	(*ReqResRatios)(nil),       // 20: ReqResRatios
	(*ResRatios)(nil),          // 21: ResRatios
}
var file_db_reqres_proto_depIdxs = []int32{
	8,  // 0: ResDeckList.decklist:type_name -> ReqResDeck
	9,  // 1: ResFavoriteList.favoriteList:type_name -> ReqResFavorities
	7,  // 2: ReqResDeck.deckDetails:type_name -> ReqResDeckDetails
	18, // 3: ResSnapshots.snapshots:type_name -> ResSnapshot
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_db_reqres_proto_init() }
func file_db_reqres_proto_init() {
	if File_db_reqres_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_reqres_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_reqres_proto_goTypes,
		DependencyIndexes: file_db_reqres_proto_depIdxs,
		MessageInfos:      file_db_reqres_proto_msgTypes,
	}.Build()
	File_db_reqres_proto = out.File
	file_db_reqres_proto_rawDesc = nil
	file_db_reqres_proto_goTypes = nil
	file_db_reqres_proto_depIdxs = nil
}
